// Generated by scripts/make-image-variants.py -- do not edit by hand.
// Photos in public/images that have thumbs/ and md/ WebP copies.
export const LOCAL_VARIANTS = new Set([
  "BigG.jpg",
  "bbq_chicken.jpg",
  "bbq_lamb.jpg",
  "bbqbeefburger.jpg",
  "cz_chix_burger.png",
  "hero_burger.png",
  "iceBB.jpg",
  "monsta_fries.jpg",
  "mushy_burger.jpg",
  "premium_platter.jpg",
  "regular_fries.png"
]);
