"""Builds small WebP copies of the photos in public/images so pages can show
a 56px thumbnail or a card without downloading a 1000px original.

  public/images/thumbs/<name>.webp  -- 192px wide (thumbnails, up to 3x screens)
  public/images/md/<name>.webp      -- 800px wide (cards, hero backgrounds)

and writes src/utils/localImageVariants.js listing which names have them.
Re-run after adding photos:  python3 scripts/make-image-variants.py
"""
import json, os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')
SRC = os.path.join(ROOT, 'public', 'images')
MIN_BYTES = 30 * 1024   # small files aren't worth a variant
SKIP_PREFIXES = ('trex_', 'ghost_', 'munchman_', 'fry_catch', 'Trex', 'logo')  # game art / already handled

names = []
for f in sorted(os.listdir(SRC)):
    base, ext = os.path.splitext(f)
    if ext.lower() not in ('.jpg', '.jpeg', '.png') or f.startswith(SKIP_PREFIXES):
        continue
    path = os.path.join(SRC, f)
    if os.path.getsize(path) < MIN_BYTES:
        continue
    im = Image.open(path)
    alpha = im.mode in ('RGBA', 'LA') or (im.mode == 'P' and 'transparency' in im.info)
    im = im.convert('RGBA' if alpha else 'RGB')
    for folder, width in (('thumbs', 192), ('md', 800)):
        os.makedirs(os.path.join(SRC, folder), exist_ok=True)
        v = im if im.width <= width else im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
        v.save(os.path.join(SRC, folder, base + '.webp'), 'WEBP', quality=80, method=6)
    names.append(f)

with open(os.path.join(ROOT, 'src', 'utils', 'localImageVariants.js'), 'w') as out:
    out.write('// Generated by scripts/make-image-variants.py -- do not edit by hand.\n')
    out.write('// Photos in public/images that have thumbs/ and md/ WebP copies.\n')
    out.write('export const LOCAL_VARIANTS = new Set(' + json.dumps(names, indent=2) + ');\n')
print(len(names), 'photos:', ', '.join(names))
